import { XYCoord } from 'react-dnd';
import { RecipeElement } from '../common/types';

export interface DragItem {
    type: string
    offset?: XYCoord
    id?: string
    element?: RecipeElement
    top?: number
    left?: number
}

export enum ItemTypes {
    ELEMENT = 'element',
    MAIN_ELEMENT = 'main',
    FINAL_ELEMENT = 'final',
    SIDE_ELEMENT = 'side',
    COPY_ELEMENT = 'copy',
    RECIPE_ELEMENT = 'recipe',
    LOCKED_ELEMENT = 'locked'
}

export interface Box {
    top: number
    left: number
    combining: boolean,
    newCombining: boolean,
    loading: boolean,
    firstDiscovery: boolean,
    newDiscovery: boolean,
    locked: boolean,
    error: number,
    element: RecipeElement
}

// The following is extracted from
// https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
export const KEY_VALUES_TO_LEAVE = [
    // Modifier
    'Alt',
    'AltGraph',
    'CapsLock',
    'Control',
    'Fn',
    'FnLock',
    'Hyper',
    'Meta',
    'NumLock',
    'ScrollLock',
    'Shift',
    'Super',
    'Symbol',
    'SymbolLock',

    // Whitespace
    'Enter',
    'Tab',

    // Navigation
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'ArrowUp',
    'End',
    'Home',
    'PageDown',
    'PageUp',

    // Editing
    'Backspace',
    'Clear',
    'Copy',
    'CrSel',
    'Cut',
    'Delete',
    'EraseEof',
    'ExSel',
    'Insert',
    'Paste',
    'Redo',
    'Undo',

    // UI
    'Accept',
    'Again',
    'Attn',
    'Cancel',
    'ContextMenu',
    'Escape',
    'Execute',
    'Find',
    'Finish',
    'Help',
    'Pause',
    'Play',
    'Props',
    'Select',
    'ZoomIn',
    'ZoomOut',

    // Device
    'BrightnessDown',
    'BrightnessUp',
    'Eject',
    'LogOff',
    'Power',
    'PowerOff',
    'PrintScreen',
    'Hibernate',
    'Standby',
    'WakeUp',

    // IME and Composition
    'AllCandidates',
    'Alphanumeric',
    'CodeInput',
    'Compose',
    'Convert',
    'Dead',
    'FinalMode',
    'GroupFirst',
    'GroupLast',
    'GroupNext',
    'GroupPrevious',
    'ModeChange',
    'NextCandidate',
    'NonConvert',
    'PreviousCandidate',
    'Process',
    'SingleCandidate',

    // Korean
    'HangulMode',
    'HanjaMode',
    'JunjaMode',

    // Japanese
    'Eisu',
    'Hankaku',
    'Hiragana',
    'HiraganaKatakana',
    'KanaMode',
    'KanjiMode',
    'Katakana',
    'Romaji',
    'Zenkaku',
    'ZenkakuHanaku',

    // Function
    'F1',
    'F2',
    'F3',
    'F4',
    'F5',
    'F6',
    'F7',
    'F8',
    'F9',
    'F10',
    'F11',
    'F12',
    'F13',
    'F14',
    'F15',
    'F16',
    'F17',
    'F18',
    'F19',
    'F20',
    'Soft1',
    'Soft2',
    'Soft3',
    'Soft4',

    // Phone
    'AppSwitch',
    'Call',
    'Camera',
    'CameraFocus',
    'EndCall',
    'GoBack',
    'GoHome',
    'HeadsetHook',
    'LastNumberRedial',
    'Notification',
    'MannerMode',
    'VoiceDial',

    // Multimedia
    'ChannelDown',
    'ChannelUp',
    'MediaFastForward',
    'MediaPause',
    'MediaPlay',
    'MediaPlayPause',
    'MediaRecord',
    'MediaRewind',
    'MediaStop',
    'MediaTrackNext',
    'MediaTrackPrevious',

    // Audio Control
    'AudioBalanceLeft',
    'AudioBalanceRight',
    'AudioBassDown',
    'AudioBassBoostDown',
    'AudioBassBoostToggle',
    'AudioBassBoostUp',
    'AudioBassUp',
    'AudioFaderFront',
    'AudioFaderRear',
    'AudioSurroundModeNext',
    'AudioTrebleDown',
    'AudioTrebleUp',
    'AudioVolumeDown',
    'AudioVolumeMute',
    'AudioVolumeUp',
    'MicrophoneToggle',
    'MicrophoneVolumeDown',
    'MicrophoneVolumeMute',
    'MicrophoneVolumeUp',

    // TV Control
    'TV',
    'TV3DMode',
    'TVAntennaCable',
    'TVAudioDescription',
    'TVAudioDescriptionMixDown',
    'TVAudioDescriptionMixUp',
    'TVContentsMenu',
    'TVDataService',
    'TVInput',
    'TVInputComponent1',
    'TVInputComponent2',
    'TVInputComposite1',
    'TVInputComposite2',
    'TVInputHDMI1',
    'TVInputHDMI2',
    'TVInputHDMI3',
    'TVInputHDMI4',
    'TVInputVGA1',
    'TVMediaContext',
    'TVNetwork',
    'TVNumberEntry',
    'TVPower',
    'TVRadioService',
    'TVSatellite',
    'TVSatelliteBS',
    'TVSatelliteCS',
    'TVSatelliteToggle',
    'TVTerrestrialAnalog',
    'TVTerrestrialDigital',
    'TVTimer',

    // Media Controller
    'AVRInput',
    'AVRPower',
    'ColorF0Red',
    'ColorF1Green',
    'ColorF2Yellow',
    'ColorF3Blue',
    'ColorF4Grey',
    'ColorF5Brown',
    'ClosedCaptionToggle',
    'Dimmer',
    'DisplaySwap',
    'DVR',
    'Exit',
    'FavoriteClear0',
    'FavoriteClear1',
    'FavoriteClear2',
    'FavoriteClear3',
    'FavoriteRecall0',
    'FavoriteRecall1',
    'FavoriteRecall2',
    'FavoriteRecall3',
    'FavoriteStore0',
    'FavoriteStore1',
    'FavoriteStore2',
    'FavoriteStore3',
    'Guide',
    'GuideNextDay',
    'GuidePreviousDay',
    'Info',
    'InstantReplay',
    'Link',
    'ListProgram',
    'LiveContent',
    'Lock',
    'MediaApps',
    'MediaAudioTrack',
    'MediaLast',
    'MediaSkipBackward',
    'MediaSkipForward',
    'MediaStepBackward',
    'MediaStepForward',
    'MediaTopMenu',
    'NavigateIn',
    'NavigateNext',
    'NavigateOut',
    'NavigatePrevious',
    'NextFavoriteChannel',
    'NextUserProfile',
    'OnDemand',
    'Pairing',
    'PinPDown',
    'PinPMove',
    'PinPToggle',
    'PinPUp',
    'PlaySpeedDown',
    'PlaySpeedReset',
    'PlaySpeedUp',
    'RandomToggle',
    'RcLowBattery',
    'RecordSpeedNext',
    'RfBypass',
    'ScanChannelsToggle',
    'ScreenModeNext',
    'Settings',
    'SplitScreenToggle',
    'STBInput',
    'STBPower',
    'Subtitle',
    'Teletext',
    'VideoModeNext',
    'Wink',
    'ZoomToggle',

    // Speed Recognition
    'SpeechCorrectionList',
    'SpeechInputToggle',

    // Document
    'Close',
    'New',
    'Open',
    'Print',
    'Save',
    'SpellCheck',
    'MailForward',
    'MailReply',
    'MailSend',

    // Application Selector
    'LaunchCalculator',
    'LaunchCalendar',
    'LaunchContacts',
    'LaunchMail',
    'LaunchMediaPlayer',
    'LaunchMusicPlayer',
    'LaunchMyComputer',
    'LaunchPhone',
    'LaunchScreenSaver',
    'LaunchSpreadsheet',
    'LaunchWebBrowser',
    'LaunchWebCam',
    'LaunchWordProcessor',
    'LaunchApplication1',
    'LaunchApplication2',
    'LaunchApplication3',
    'LaunchApplication4',
    'LaunchApplication5',
    'LaunchApplication6',
    'LaunchApplication7',
    'LaunchApplication8',
    'LaunchApplication9',
    'LaunchApplication10',
    'LaunchApplication11',
    'LaunchApplication12',
    'LaunchApplication13',
    'LaunchApplication14',
    'LaunchApplication15',
    'LaunchApplication16',

    // Browser Control
    'BrowserBack',
    'BrowserFavorites',
    'BrowserForward',
    'BrowserHome',
    'BrowserRefresh',
    'BrowserSearch',
    'BrowserStop',

    // Numeric Keypad
    'Decimal',
    'Key11',
    'Key12',
    'Multiply',
    'Add',
    'Clear',
    'Divide',
    'Subtract',
    'Separator',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9'
];
