name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release version (with v)'
        required: false
        default: ''
        type: string
      # includePrerelease:
      #   description: 'Whether or not to include prerelease when getting latest'
      #   required: false
      #   default: true
      #   type: boolean

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Create folders
      run: |
        mkdir -p ./out/win32/
        mkdir -p ./out/linux/
    - name: Debug used variables
      run: |
        echo $github
        echo $prerelease
        echo $created
      env:
        github: ${{ tojson(github) }}
        prerelease: ${{ github.event.release.prerelease }}
        created: ${{ github.event.release.created_at }}
    - name: Download linux zip
      uses: robinraju/release-downloader@v1.8
      with: 
        latest: ${{ github.event.inputs.releaseTag == '' }}
        # preRelease: ${{ github.event.inputs.includePrerelease }}
        tag: ${{ github.event.inputs.releaseTag }}
        # The name of the file to download.
        # Use this field only to specify filenames other than tarball or zipball, if any.
        # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
        fileName: "alchemy-unbound-*.zip"
        out-file-path: "out"
        extract: false
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Download linux zip
    #   uses: robinraju/release-downloader@v1.8
    #   with: 
    #     latest: ${{ github.event.inputs.releaseTag == '' }}
    #     # preRelease: ${{ github.event.inputs.includePrerelease }}
    #     tag: ${{ github.event.inputs.releaseTag }}
    #     # The name of the file to download.
    #     # Use this field only to specify filenames other than tarball or zipball, if any.
    #     # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
    #     fileName: "alchemy-unbound-linux*.zip"
    #     out-file-path: "out/linux"
    #     extract: false
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #- name: Download windows zip
    #  uses: robinraju/release-downloader@v1.8
    #  with: 
    #    latest: ${{ github.event.inputs.releaseTag == '' }}
    #    # preRelease: ${{ github.event.inputs.includePrerelease }}
    #    tag: ${{ github.event.inputs.releaseTag }}
    #    # The name of the file to download.
    #    # Use this field only to specify filenames other than tarball or zipball, if any.
    #    # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
    #    fileName: "alchemy-unbound-win32*.zip"
    #    out-file-path: "out/windows"
    #    extract: false
    #    token: ${{ secrets.GITHUB_TOKEN }}
    - name: Debug used variables
      run: |
          echo $github
          echo $prerelease
          echo $created
      env:
          github: ${{ tojson(github) }}
          prerelease: ${{ github.event.release.prerelease }}
          created: ${{ github.event.release.created_at }}
    - name: extract things
      run: |
        unzip -o ./out/alchemy-unbound-linux*.zip -d ./out/linux || true
        zip -FF ./out/alchemy-unbound-win32*.zip --out ./out/alchemy-unbound-win32-fixed.zip -fz || true
        unzip -o ./out/alchemy-unbound-win32-fixed.zip -d ./out/win32/alchemy-unbound-win32-x64 || true
    - name: Debug dirs
      run: |
        ls out
        ls out/linux
        ls out/win32
        ls out/linux/alchemy-unbound-linux-x64
        ls out/win32/alchemy-unbound-win32-x64
    - uses: cardinalby/git-get-release-action@v1
      id: release
      with:
        tag: ${{ github.event.inputs.releaseTag }}         
        searchLimit: 20
    - name: Set prerelease branch
      if: ${{ steps.release.output.prerelease }}
      run: echo 'RELEASE_BRANCH=prerelease' >> "$GITHUB_ENV"
    - name: Set release branch
      if: ${{ !steps.release.output.prerelease }}
      run: echo 'RELEASE_BRANCH=release' >> "$GITHUB_ENV"
    #- uses: game-ci/steam-deploy@v3
    #  with:
    #    username: ${{ secrets.STEAM_USERNAME }}          
    #    configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
    #    appId: 2858840
    #    buildDescription: ${{ github.event.inputs.releaseTag }}
    #    rootPath: out
    #    depot2Path: alchemy-unbound-win32-x64
    #    depot3Path: alchemy-unbound-linux-x64
    #    releaseBranch: ${{ env.RELEASE_BRANCH }}
