name: Release

on:
    release:
        types: [published]
#  push:
#    tags:
#      - v*

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get commits since version
        id: commits
        run: echo "value=$(git log "$(git describe --tags --abbrev=0)..HEAD" --no-merges --oneline)" >> $GITHUB_STATE
      - name: Debug used variables
        run: |
            echo $github
            echo $prerelease
            echo $created
        env:
            github: ${{ tojson(github) }}
            prerelease: ${{ github.event.release.prerelease }}
            created: ${{ github.event.release.created_at }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
            node-version: 18.x
      - name: Install dependacnies
        run: npm ci
      - name: Build for ${{ matrix.os }}
        run: npm run make
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            out/make/zip/**/*

      - name: Set prerelease branch
        if: github.event.release.prerelease
        run: echo 'RELEASE_BRANCH=prerelease' >> "$GITHUB_ENV"
      - name: Set release branch
        if: not github.event.release.prerelease
        run: echo 'RELEASE_BRANCH=release' >> "$GITHUB_ENV"
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}          
          appId: 2858840
          buildDescription: ${{ github.event.release.tag_name }}
          rootPath: out
          depot2Path: alchemy-unbound-win32-x64
          depot3Path: alchemy-unbound-linux-x64
          releaseBranch: ${{ env.RELEASE_BRANCH }}
